Deleting the Old template first now
catawiki/ios-xcode-app-module-template pull request #17
Opened 2020-11-16 18:11 UTC by crazymanish

Background Context: 
- https://catawiki.slack.com/archives/GEZ3TGV8W/p1605546991053000 

How to test:
- Open terminal and go-to Xcode template path i.e `cd ~/Library/Developer/Xcode/Templates/File\ Templates/Source`
- Delete all the existing templates from Source folder
- Run `sh install.sh` 

You should not below error message on the console:
<img width="1049" alt="Screenshot 2020-11-16 at 18 15 09" src="https://user-images.githubusercontent.com/5364500/99291055-82f3d280-283f-11eb-82c4-24098e94a8d0.png">

2020-12-01 16:21 UTC, mvandervelden requested changes
See comment

2020-12-01 16:21 UTC, mvandervelden commented on install.sh
> +rm -r "${TEMPLATE_PATH}"
We shouldn't do this I think, as it will also remove templates you installed from other sources than this repo.
In general, if the path is not fully under the control of the project, it's pretty scary to just completely remove the folder.

In the old solution this was not a real problem, because we were only removing templates that we would actually replace anyway.

I actually prefer to have a warning that the removed folder doesn't exist, instead of this. Perhaps to avoid the warning we could just add a flag to rm to fail silently, or pipe the response to null or smth.

2020-12-02 09:26 UTC, crazymanish commented on install.sh
> +rm -r "${TEMPLATE_PATH}"
I agree! I did not realize that its a shared folder 😅

> Perhaps to avoid the warning we could just add a flag to rm to fail silently, or pipe the response to null or smth.

I will apply this suggestion, thank you for the review and suggestion. 🙇

2020-12-02 12:13 UTC, mvandervelden approved these changes

2020-12-15 10:24 UTC, merged